---
title: Advanced R Workshop, IISA 2022
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Material for the [Advanced R](https://www.intindstat.org/conference2022/shortCourses) workshop held at the 2022 International Indian Statistical Association Conference, [IISA 2022](https://www.intindstat.org/conference2022/index).

## Overview

Writing functions in R enables you to work more efficiently by writing code for re-use in routine analyses. It also equips you to run simulations and implement novel or customised methods. This workshop will provide a hands-on experience for participants to move on from the basics of writing a function in R, learning how write robust and efficient code that incorporates good software engineering practices. We will discuss how such functions could form the basis of an R package for private use or public distribution with an open source license.

## Schedule

1:30 - 3:00 Part I: [slides](https://hturner.github.io/IISA2022/01_developing_r_functions.html#1) | [exercises](/exercises)

 * [Opening Remarks](https://hturner.github.io/IISA2022/00_advanced_r.html#1)
 * [Developing R Functions](https://hturner.github.io/IISA2022/01_developing_r_functions.html#1)
    * Components of a function and design considerations
    * Using functions from other packages in your functions
    * Documenting functions
    * Unit testing
    * Error Handling
    * Debugging

3:00 - 3:30 Coffee break (provided by IISA)

3:30 - 5:00 Part II: [slides](https://hturner.github.io/IISA2022/02_efficient_code.html#1)

  * [Efficient programming](https://hturner.github.io/IISA2022/02_efficient_code.html#1)
     * Memory management
     * Benchmarking
     * Vectorization
     * Profiling code
  * Going further: outlook to package development
  
[Solutions](/solutions) to exercises in both parts.

## Pre-requisites

Participants should be comfortable with handling basic data structures in R (e.g., creating/indexing vectors and matrices) and familiar with flow control (e.g. using if/else blocks of code).

## References:

Wickham, H. [Advanced R (2nd edn)](https://adv-r.hadley.nz/)

Gillespie, C and Lovelace, R. [Efficient R programming](https://csgillespie.github.io/efficientR/)
